export const LABELS = {
  ecología: "ecología",
  ecologías: "ecología",
  ecológico: "ecología",
  ecológicos: "ecología",
  reutilizable: "ecología",
  reutilizables: "ecología",
  sostenible: "ecología",
  sostenibles: "ecología",
  "medio ambiente": "ecología",
  ambientales: "ecología",
  reciclado: "ecología",
  reciclados: "ecología",
  "energías renovables": "ecología",
  medicina: "medicina",
  salud: "medicina",
  ambulancia: "medicina",
  ambulancias: "medicina",
  saludable: "medicina",
  covid: "medicina",
  medicos: "medicina",
  coronavirus: "medicina",
  hospital: "medicina",
  doctor: "medicina",
  farmacia: "medicina",
  clínica: "medicina",
  bienestar: "medicina",
  cirugia: "medicina",
  enfermeria: "medicina",
  calidaddevida: "medicina",
  nutrición: "medicina",
  vidasana: "medicina",
  cuarentena: "medicina",
  saludables: "medicina",
  dieta: "medicina",
  ejercicio: "medicina",
  economía: "economía",
  economías: "economía",
  "planes sociales": "economía",
  "plan de ahorro": "economía",
  emprendimientos: "economía",
  pyme: "economía",
  pymes: "economía",
  producción: "economía",
  "sector productivo": "economía",
  industria: "economía",
  industrias: "economía",
  negocio: "economía",
  negocios: "economía",
  inversión: "economía",
  inversiones: "economía",
  dinero: "economía",
  banco: "economía",
  bancos: "economía",
  ahorristas: "economía",
  dólares: "economía",
  inclusíon: "inclusíon",
  "inclusíon social": "inclusíon",
  trans: "inclusíon",
  "identidad de género": "inclusíon",
  minorías: "inclusíon",
  transporte: "transporte",
  logística: "transporte",
  urbanización: "transporte",
  vehículo: "transporte",
  vehículos: "transporte",
  bicleta: "transporte",
  bicisenda: "transporte",
  peatones: "transporte",
  peatonal: "transporte",
  peatón: "transporte",
  semáforo: "transporte",
  semáforos: "transporte",
  vía: "transporte",
  "transporte público": "transporte",
  tren: "transporte",
  trenes: "transporte",
  colectivo: "transporte",
  taxi: "transporte",
  taxis: "transporte",
};
